### ISSUE TITLE
How to solve the running error: RuntimeError: The cuda env is set before the forked thread starts. Please do not use any cuda function or variable before forking.

### ISSUE THREAD

**Issue by zhengzehao123** [megvii-research/FullMatch#2]
(fullmatch) root@88aab7fff62e:~/zhengzh/FullMatch# python fullflex.py --c config/fullflex/fullflex_cifar100.yaml
/root/zhengzh/FullMatch/fullflex.py:191: DeprecationWarning: Call to deprecated function get_device_count. (use megengine.device.get_device_count instead) -- Deprecated since version 1.5.
  args.ngpus = dist.helper.get_device_count_by_fork('gpu')
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/envs/fullmatch/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/envs/fullmatch/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/fullmatch/lib/python3.10/site-packages/megengine/distributed/launcher.py", line 37, in _run_wrapped
    _check_device_initialized(device_type, dev)
  File "/opt/conda/envs/fullmatch/lib/python3.10/site-packages/megengine/distributed/helper.py", line 162, in _check_device_initialized
    raise RuntimeError(errmsg)
RuntimeError: The cuda env is set before the forked thread starts. Please do not use any cuda function or variable before forking.
Process Process-3:
Traceback (most recent call last):
  File "/opt/conda/envs/fullmatch/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/envs/fullmatch/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/fullmatch/lib/python3.10/site-packages/megengine/distributed/launcher.py", line 37, in _run_wrapped
    _check_device_initialized(device_type, dev)
  File "/opt/conda/envs/fullmatch/lib/python3.10/site-packages/megengine/distributed/helper.py", line 162, in _check_device_initialized
    raise RuntimeError(errmsg)
RuntimeError: The cuda env is set before the forked thread starts. Please do not use any cuda function or variable before forking.
Traceback (most recent call last):
  File "/root/zhengzh/FullMatch/fullflex.py", line 202, in <module>
    dist_worker(args)
  File "/opt/conda/envs/fullmatch/lib/python3.10/site-packages/megengine/distributed/launcher.py", line 150, in __call__
    code == 0 or code == None
AssertionError: subprocess 0 exit with code 1

**Comment by yhaochen0617** [comment]
抱歉，刚看到。
RuntimeError: The cuda env is set before the forked thread starts. Please do not use any cuda function or variable before forking

看起来像是在fork子进程之前调用了cuda相关的函数，可以检查下megenegine的版本或者code

**Comment by yhaochen0617** [comment]
sorry for the late replying.

RuntimeError: The cuda env is set before the forked thread starts. Please do not use any cuda function or variable before forking.

it looks like cuda functions are called before the fork child process. please check megengine version or code.
if having more issues, please feel free to concat with me (yhao.chen0617@gmail.com)
